kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: koku-metrics-operator

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources: 
 - namespace.yaml
 - operator-group.yaml
 - ../../base/operator
 - ../../base/instance