apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
  - ../../base

components:
  - ../../components/components-serving
  - ../../components/components-training
  - ../../components/components-trustyai
  - ../../components/default-notebook-pvc-size
  - ../../components/idle-notebook-culling
  - ../../components/notebook-pod-sizes
  - ../../components/nvidia-gpu-accelerator-profile
  - ../../components/make-kubeadmin-cluster-admin
  - ../../components/model-server-pod-sizes
  - ../../components/rhoai-dashboard-access
  - ../../components/auth-with-authorino
