apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gatekeeper-operator

resources:
  - namespace.yaml
  - gatekeeper-subscription.yaml
  - gatekeeper-operatorgroup.yaml
  - gatekeeper-catalogsource.yaml


