apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-operator

resources:
  - redhat-ods-operator-namespace.yaml
  - redhat-ods-operator-operatorgroup.yaml
  - rhods-operator-subscription.yaml
