---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
- 06-sealed-ansible-tower-inventory.yaml

patches:
-  target:
     kind: PersistentVolumeClaim
     name: tower-postgresql
   patch: |-
    - op: replace
      path: /spec/storageClassName
      value: 'gp2'
-  target:
     kind: ConsoleLink
     name: tower
   patch: |-
    - op: replace
      path: /spec/href
      value: 'https://ansible-tower-web-svc-openshift-ansible.apps.hub-adetalhouet.rhtelco.io'