kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../default

patchesJson6902:
  - path: patch-source-and-name.yaml
    target:
      group: koku-metrics-cfg.openshift.io
      kind: KokuMetricsConfig
      name: instance
      version: v1beta1
