kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Include the base Sealed Secrets manifests.
bases:
- ../../base

# Create a role and binding for the Sealed Secrets controller that will give it "anyuid" access.
resources:
- role-anyuid.yaml
