---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: namespace-configuration-operator


resources:
  - namespace.yaml
  - operator-group.yaml
  - ../../base
  - ../../../installplan-approver/base
