apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

resources:
- create-cluster-init-bundle-sa.yaml
- central.yaml
- create-cluster-init-bundle-job.yaml
- secured-cluster.yaml