apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql-data-pvc.yaml
  - postgresql-dc.yaml
  - postgresql-svc.yaml
  - sonarqube-data-pvc.yaml
  - sonarqube-deployment.yaml
  - sonarqube-route.yaml
  - sonarqube-svc.yaml
