apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

components:
  - ../../components/annotation-resource-tracking
  - ../../components/application-controller-cluster-admin
  - ../../components/gitops-admins
  - ../../components/edge-termination
  - ../../components/enable-notifications
  - ../../components/health-check-odf
  - ../../components/health-check-olm
  - ../../components/health-check-openshift-builds
  - ../../components/kustomize-build-enable-helm

patches:
- path: gitops-admins-group.yaml
