apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - subscription.yaml

# patches:
#   - target:
#       kind: Subscription
#       name: cluster-observability-operator
#     path: patch-channel.yaml
