apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ack-system

resources:
  - ../../instance
  - ../../../ack-ec2-controller/operator/overlays/alpha
  - ../../../ack-ecr-controller/operator/overlays/alpha
  - ../../../ack-iam-controller/operator/overlays/alpha
  - ../../../ack-lambda-controller/operator/overlays/alpha
  - ../../../ack-route53-controller/operator/overlays/alpha
  - ../../../ack-s3-controller/operator/overlays/alpha
  - ../../../ack-sagemaker-controller/operator/overlays/alpha
