apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhsso-operatorgroup.yaml
  - rhsso-subscription.yaml
  - approval-and-cert-job.yaml
  - serviceaccount.yaml
  - rbac.yaml
