apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-sandboxed-containers-operator

bases:
- ../../base

patchesStrategicMerge:
- openshift-sandboxed-containers-operator-sub.yaml
