apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-gitops

resources:
- console-plugin-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-gitops-console-plugin
    files:
      - console-plugin-job.sh
