apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators


patches:
- path: patch-channel.yaml
  target:
    group: operators.coreos.com
    kind: Subscription
    name: seldon-operator-certified
    version: v1alpha1
resources:
- ../../base
