apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jenkins-dc.yaml
  - jenkins-jnlp.yaml
  - jenkins-pvc.yaml
  - jenkins-rolebinding.yaml
  - jenkins-route.yaml
  - jenkins-sa.yaml
  - jenkins-svc.yaml
