apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-local-storage

bases:
  - ../../base

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: local-storage-operator
      namespace: openshift-local-storage
    path: patch-channel.yaml
