apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: devspaces

namespace: devspaces

resources:
  - checluster.yaml
  - devworkspace-config.yaml
  - namespace.yaml
