apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-build-health-check.yaml
    target:
      kind: ArgoCD
  - path: patch-imagestream-health-check.yaml
    target:
      kind: ArgoCD
