apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-sandboxed-containers-operator

resources:
- openshift-sandboxed-containers-operator-ns.yaml
- openshift-sandboxed-containers-operator-og.yaml
- openshift-sandboxed-containers-operator-sub.yaml
