kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-compliance

bases:
  - ../../base

patches:
-  target:
     kind: Subscription
     name: rhacs-operator
   patch: |-
    - op: replace
      path: /spec/channel
      value: 'latest'
